name: Deploy Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python 3.13
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: pip install tox
      - name: Test with tox
        run: tox -e py,flake8,black
      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v3
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate SAM template
        run: sam validate --lint --region eu-west-1
      - name: Build Lambda functions
        run: sam build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_PROD }}:role/github-deploy
          aws-region: eu-west-1
      - name: Sts GetCallerIdentity
        run: aws sts get-caller-identity
      - name: Deploy Lambda functions
        run: sam deploy --config-env prod --parameter-overrides "Stage=prod GitRev=${GITHUB_REF_NAME}:${GITHUB_SHA::7}"
